### ISSUE TITLE
generate qrcode to stdin

### ISSUE THREAD

**Issue by vmath3us** [Anant-mishra1729/qrcopy#3]
add option to qrcode stdin, example
cat file | qrcopy -s (to copy content on smartphone)
command | curl -F 'file=@-' 0x0.st | qrcopy -s (send output first command to 0x0, and gen qrcode to link)
strace command | curl -F 'file=@-' 0x0.st  | qrcopy -s (send log to 0x0, and gen qrcode to link)
curl -F'file=@yourfile.png' 0x0.st | qrcopy -s (upload file to 0x0 and gen qrcode to link)

**Comment by Anant-mishra1729** [comment]
Thanks for the suggestion, this feature is implemented now.
Please test and report, if any bug occurs.
